/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing AggCompositeTerm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AggCompositeTermTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AggCompositeTerm
        //private AggCompositeTerm instance;

        public AggCompositeTermTests()
        {
            // TODO uncomment below to create an instance of AggCompositeTerm
            //instance = new AggCompositeTerm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AggCompositeTerm
        /// </summary>
        [Fact]
        public void AggCompositeTermInstanceTest()
        {
            // TODO uncomment below to test "IsType" AggCompositeTerm
            //Assert.IsType<AggCompositeTerm>(instance);
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }
    }
}
