/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing AggDateHistogram
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AggDateHistogramTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AggDateHistogram
        //private AggDateHistogram instance;

        public AggDateHistogramTests()
        {
            // TODO uncomment below to create an instance of AggDateHistogram
            //instance = new AggDateHistogram();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AggDateHistogram
        /// </summary>
        [Fact]
        public void AggDateHistogramInstanceTest()
        {
            // TODO uncomment below to test "IsType" AggDateHistogram
            //Assert.IsType<AggDateHistogram>(instance);
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Fact]
        public void IntervalTest()
        {
            // TODO unit test for the property 'Interval'
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }

        /// <summary>
        /// Test the property 'Keyed'
        /// </summary>
        [Fact]
        public void KeyedTest()
        {
            // TODO unit test for the property 'Keyed'
        }
    }
}
