/*
 * Manticore Search Client
 *
 * Low-level client for Manticore Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing Aggregation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AggregationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Aggregation
        //private Aggregation instance;

        public AggregationTests()
        {
            // TODO uncomment below to create an instance of Aggregation
            //instance = new Aggregation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Aggregation
        /// </summary>
        [Fact]
        public void AggregationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Aggregation
            //Assert.IsType<Aggregation>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

    }

}
