/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing AggregationComposite
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AggregationCompositeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AggregationComposite
        //private AggregationComposite instance;

        public AggregationCompositeTests()
        {
            // TODO uncomment below to create an instance of AggregationComposite
            //instance = new AggregationComposite();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AggregationComposite
        /// </summary>
        [Fact]
        public void AggregationCompositeInstanceTest()
        {
            // TODO uncomment below to test "IsType" AggregationComposite
            //Assert.IsType<AggregationComposite>(instance);
        }


        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Sources'
        /// </summary>
        [Fact]
        public void SourcesTest()
        {
            // TODO unit test for the property 'Sources'
        }

    }

}
