/*
 * Manticore Search Client
 *
 * Low-level client for Manticore Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing Facet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FacetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Facet
        //private Facet instance;

        public FacetTests()
        {
            // TODO uncomment below to create an instance of Facet
            //instance = new Facet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Facet
        /// </summary>
        [Fact]
        public void FacetInstanceTest()
        {
            // TODO uncomment below to test "IsType" Facet
            //Assert.IsType<Facet>(instance);
        }


        /// <summary>
        /// Test the property 'Attr'
        /// </summary>
        [Fact]
        public void AttrTest()
        {
            // TODO unit test for the property 'Attr'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Fact]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

    }

}
