/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing HitsHits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HitsHitsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HitsHits
        //private HitsHits instance;

        public HitsHitsTests()
        {
            // TODO uncomment below to create an instance of HitsHits
            //instance = new HitsHits();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HitsHits
        /// </summary>
        [Fact]
        public void HitsHitsInstanceTest()
        {
            // TODO uncomment below to test "IsType" HitsHits
            //Assert.IsType<HitsHits>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'KnnDist'
        /// </summary>
        [Fact]
        public void KnnDistTest()
        {
            // TODO unit test for the property 'KnnDist'
        }

        /// <summary>
        /// Test the property 'Highlight'
        /// </summary>
        [Fact]
        public void HighlightTest()
        {
            // TODO unit test for the property 'Highlight'
        }

        /// <summary>
        /// Test the property 'Table'
        /// </summary>
        [Fact]
        public void TableTest()
        {
            // TODO unit test for the property 'Table'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
    }
}
