/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing KnnQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KnnQueryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KnnQuery
        //private KnnQuery instance;

        public KnnQueryTests()
        {
            // TODO uncomment below to create an instance of KnnQuery
            //instance = new KnnQuery();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KnnQuery
        /// </summary>
        [Fact]
        public void KnnQueryInstanceTest()
        {
            // TODO uncomment below to test "IsType" KnnQuery
            //Assert.IsType<KnnQuery>(instance);
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'K'
        /// </summary>
        [Fact]
        public void KTest()
        {
            // TODO unit test for the property 'K'
        }

        /// <summary>
        /// Test the property 'QueryVector'
        /// </summary>
        [Fact]
        public void QueryVectorTest()
        {
            // TODO unit test for the property 'QueryVector'
        }

        /// <summary>
        /// Test the property 'DocId'
        /// </summary>
        [Fact]
        public void DocIdTest()
        {
            // TODO unit test for the property 'DocId'
        }

        /// <summary>
        /// Test the property 'Ef'
        /// </summary>
        [Fact]
        public void EfTest()
        {
            // TODO unit test for the property 'Ef'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
    }
}
