/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing KnnQueryByVector
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KnnQueryByVectorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KnnQueryByVector
        //private KnnQueryByVector instance;

        public KnnQueryByVectorTests()
        {
            // TODO uncomment below to create an instance of KnnQueryByVector
            //instance = new KnnQueryByVector();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KnnQueryByVector
        /// </summary>
        [Fact]
        public void KnnQueryByVectorInstanceTest()
        {
            // TODO uncomment below to test "IsType" KnnQueryByVector
            //Assert.IsType<KnnQueryByVector>(instance);
        }


        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }
        /// <summary>
        /// Test the property 'QueryVector'
        /// </summary>
        [Fact]
        public void QueryVectorTest()
        {
            // TODO unit test for the property 'QueryVector'
        }
        /// <summary>
        /// Test the property 'K'
        /// </summary>
        [Fact]
        public void KTest()
        {
            // TODO unit test for the property 'K'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

    }

}
