/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing KnnQueryByDocId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KnnQueryByDocIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KnnQueryByDocId
        //private KnnQueryByDocId instance;

        public KnnQueryByDocIdTests()
        {
            // TODO uncomment below to create an instance of KnnQueryByDocId
            //instance = new KnnQueryByDocId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KnnQueryByDocId
        /// </summary>
        [Fact]
        public void KnnQueryByDocIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" KnnQueryByDocId
            //Assert.IsType<KnnQueryByDocId>(instance);
        }


        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }
        /// <summary>
        /// Test the property 'DocId'
        /// </summary>
        [Fact]
        public void DocIdTest()
        {
            // TODO unit test for the property 'DocId'
        }
        /// <summary>
        /// Test the property 'K'
        /// </summary>
        [Fact]
        public void KTest()
        {
            // TODO unit test for the property 'K'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

    }

}
