/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing Knn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KnnTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Knn
        //private Knn instance;

        public KnnTests()
        {
            // TODO uncomment below to create an instance of Knn
            //instance = new Knn();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Knn
        /// </summary>
        [Fact]
        public void KnnInstanceTest()
        {
            // TODO uncomment below to test "IsType" Knn
            //Assert.IsType<Knn>(instance);
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'K'
        /// </summary>
        [Fact]
        public void KTest()
        {
            // TODO unit test for the property 'K'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'QueryVector'
        /// </summary>
        [Fact]
        public void QueryVectorTest()
        {
            // TODO unit test for the property 'QueryVector'
        }

        /// <summary>
        /// Test the property 'DocId'
        /// </summary>
        [Fact]
        public void DocIdTest()
        {
            // TODO unit test for the property 'DocId'
        }

        /// <summary>
        /// Test the property 'Ef'
        /// </summary>
        [Fact]
        public void EfTest()
        {
            // TODO unit test for the property 'Ef'
        }

        /// <summary>
        /// Test the property 'Rescore'
        /// </summary>
        [Fact]
        public void RescoreTest()
        {
            // TODO unit test for the property 'Rescore'
        }

        /// <summary>
        /// Test the property 'Oversampling'
        /// </summary>
        [Fact]
        public void OversamplingTest()
        {
            // TODO unit test for the property 'Oversampling'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
    }
}
