/*
 * Manticore Search Client
 *
 * Low-level client for Manticore Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing MatchOpFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchOpFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchOpFilter
        //private MatchOpFilter instance;

        public MatchOpFilterTests()
        {
            // TODO uncomment below to create an instance of MatchOpFilter
            //instance = new MatchOpFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchOpFilter
        /// </summary>
        [Fact]
        public void MatchOpFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatchOpFilter
            //Assert.IsType<MatchOpFilter>(instance);
        }


        /// <summary>
        /// Test the property 'QueryString'
        /// </summary>
        [Fact]
        public void QueryStringTest()
        {
            // TODO unit test for the property 'QueryString'
        }
        /// <summary>
        /// Test the property 'QueryFields'
        /// </summary>
        [Fact]
        public void QueryFieldsTest()
        {
            // TODO unit test for the property 'QueryFields'
        }
        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Fact]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }

    }

}
