/*
 * Manticore Search Client
 *
 * Low-level client for Manticore Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing MatchOp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchOpTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchOp
        //private MatchOp instance;

        public MatchOpTests()
        {
            // TODO uncomment below to create an instance of MatchOp
            //instance = new MatchOp();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchOp
        /// </summary>
        [Fact]
        public void MatchOpInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatchOp
            //Assert.IsType<MatchOp>(instance);
        }


        /// <summary>
        /// Test the property 'QueryInfo'
        /// </summary>
        [Fact]
        public void QueryInfoTest()
        {
            // TODO unit test for the property 'QueryInfo'
        }

    }

}
