/*
 * Manticore Search Client
 *
 * Low-level client for Manticore Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing NotFilterString
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotFilterStringTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NotFilterString
        //private NotFilterString instance;

        public NotFilterStringTests()
        {
            // TODO uncomment below to create an instance of NotFilterString
            //instance = new NotFilterString();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotFilterString
        /// </summary>
        [Fact]
        public void NotFilterStringInstanceTest()
        {
            // TODO uncomment below to test "IsType" NotFilterString
            //Assert.IsType<NotFilterString>(instance);
        }


        /// <summary>
        /// Test the property 'FilterField'
        /// </summary>
        [Fact]
        public void FilterFieldTest()
        {
            // TODO unit test for the property 'FilterField'
        }
        /// <summary>
        /// Test the property 'Operation'
        /// </summary>
        [Fact]
        public void OperationTest()
        {
            // TODO unit test for the property 'Operation'
        }
        /// <summary>
        /// Test the property 'FilterValue'
        /// </summary>
        [Fact]
        public void FilterValueTest()
        {
            // TODO unit test for the property 'FilterValue'
        }

    }

}
