/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing QueryFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueryFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QueryFilter
        //private QueryFilter instance;

        public QueryFilterTests()
        {
            // TODO uncomment below to create an instance of QueryFilter
            //instance = new QueryFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueryFilter
        /// </summary>
        [Fact]
        public void QueryFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" QueryFilter
            //Assert.IsType<QueryFilter>(instance);
        }

        /// <summary>
        /// Test the property 'QueryString'
        /// </summary>
        [Fact]
        public void QueryStringTest()
        {
            // TODO unit test for the property 'QueryString'
        }

        /// <summary>
        /// Test the property 'Match'
        /// </summary>
        [Fact]
        public void MatchTest()
        {
            // TODO unit test for the property 'Match'
        }

        /// <summary>
        /// Test the property 'MatchPhrase'
        /// </summary>
        [Fact]
        public void MatchPhraseTest()
        {
            // TODO unit test for the property 'MatchPhrase'
        }

        /// <summary>
        /// Test the property 'MatchAll'
        /// </summary>
        [Fact]
        public void MatchAllTest()
        {
            // TODO unit test for the property 'MatchAll'
        }

        /// <summary>
        /// Test the property 'Bool'
        /// </summary>
        [Fact]
        public void BoolTest()
        {
            // TODO unit test for the property 'Bool'
        }

        /// <summary>
        /// Test the property 'PropertyEquals'
        /// </summary>
        [Fact]
        public void PropertyEqualsTest()
        {
            // TODO unit test for the property 'PropertyEquals'
        }

        /// <summary>
        /// Test the property 'In'
        /// </summary>
        [Fact]
        public void InTest()
        {
            // TODO unit test for the property 'In'
        }

        /// <summary>
        /// Test the property 'Range'
        /// </summary>
        [Fact]
        public void RangeTest()
        {
            // TODO unit test for the property 'Range'
        }

        /// <summary>
        /// Test the property 'GeoDistance'
        /// </summary>
        [Fact]
        public void GeoDistanceTest()
        {
            // TODO unit test for the property 'GeoDistance'
        }
    }
}
