/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing Range
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RangeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Range
        //private Range instance;

        public RangeTests()
        {
            // TODO uncomment below to create an instance of Range
            //instance = new Range();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Range
        /// </summary>
        [Fact]
        public void RangeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Range
            //Assert.IsType<Range>(instance);
        }

        /// <summary>
        /// Test the property 'Lt'
        /// </summary>
        [Fact]
        public void LtTest()
        {
            // TODO unit test for the property 'Lt'
        }

        /// <summary>
        /// Test the property 'Lte'
        /// </summary>
        [Fact]
        public void LteTest()
        {
            // TODO unit test for the property 'Lte'
        }

        /// <summary>
        /// Test the property 'Gt'
        /// </summary>
        [Fact]
        public void GtTest()
        {
            // TODO unit test for the property 'Gt'
        }

        /// <summary>
        /// Test the property 'Gte'
        /// </summary>
        [Fact]
        public void GteTest()
        {
            // TODO unit test for the property 'Gte'
        }
    }
}
