/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing ReplaceDocumentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReplaceDocumentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReplaceDocumentRequest
        //private ReplaceDocumentRequest instance;

        public ReplaceDocumentRequestTests()
        {
            // TODO uncomment below to create an instance of ReplaceDocumentRequest
            //instance = new ReplaceDocumentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReplaceDocumentRequest
        /// </summary>
        [Fact]
        public void ReplaceDocumentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReplaceDocumentRequest
            //Assert.IsType<ReplaceDocumentRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Doc'
        /// </summary>
        [Fact]
        public void DocTest()
        {
            // TODO unit test for the property 'Doc'
        }

    }

}
