/*
 * Manticore Search Client
 *
 * Low-level client for Manticore Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing SortMultiple
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SortMultipleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SortMultiple
        //private SortMultiple instance;

        public SortMultipleTests()
        {
            // TODO uncomment below to create an instance of SortMultiple
            //instance = new SortMultiple();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SortMultiple
        /// </summary>
        [Fact]
        public void SortMultipleInstanceTest()
        {
            // TODO uncomment below to test "IsType" SortMultiple
            //Assert.IsType<SortMultiple>(instance);
        }


        /// <summary>
        /// Test the property 'Attrs'
        /// </summary>
        [Fact]
        public void AttrsTest()
        {
            // TODO unit test for the property 'Attrs'
        }
        /// <summary>
        /// Test the property 'Replace'
        /// </summary>
        [Fact]
        public void ReplaceTest()
        {
            // TODO unit test for the property 'Replace'
        }

    }

}
