/*
 * Manticore Search Client
 *
 * Low-level client for Manticore Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing SortMVA
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SortMVATests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SortMVA
        //private SortMVA instance;

        public SortMVATests()
        {
            // TODO uncomment below to create an instance of SortMVA
            //instance = new SortMVA();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SortMVA
        /// </summary>
        [Fact]
        public void SortMVAInstanceTest()
        {
            // TODO uncomment below to test "IsType" SortMVA
            //Assert.IsType<SortMVA>(instance);
        }


        /// <summary>
        /// Test the property 'Attr'
        /// </summary>
        [Fact]
        public void AttrTest()
        {
            // TODO unit test for the property 'Attr'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

    }

}
