/*
 * Manticore Search Client
 *
 * Low-level client for Manticore Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManticoreSearch.Api;
using ManticoreSearch.Model;
using ManticoreSearch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ManticoreSearch.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateResponse
        //private UpdateResponse instance;

        public UpdateResponseTests()
        {
            // TODO uncomment below to create an instance of UpdateResponse
            //instance = new UpdateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateResponse
        /// </summary>
        [Fact]
        public void UpdateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateResponse
            //Assert.IsType<UpdateResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

    }

}
