/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ManticoreSearch.Client.FileParameter;
using OpenAPIDateConverter = ManticoreSearch.Client.OpenAPIDateConverter;

namespace ManticoreSearch.Model
{
    /// <summary>
    /// Object containing terms used for composite aggregation.
    /// </summary>
    [DataContract(Name = "aggCompositeSource")]
    public partial class AggCompositeSource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AggCompositeSource" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AggCompositeSource() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AggCompositeSource" /> class.
        /// </summary>
        /// <param name="terms">terms (required).</param>
        public AggCompositeSource(AggCompositeTerm terms = default)
        {
            // to ensure "terms" is required (not null)
            if (terms == null)
            {
                throw new ArgumentNullException("terms is a required property for AggCompositeSource and cannot be null");
            }
            this.Terms = terms;
        }

        /// <summary>
        /// Gets or Sets Terms
        /// </summary>
        [DataMember(Name = "terms", IsRequired = true, EmitDefaultValue = true)]
        public AggCompositeTerm Terms { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AggCompositeSource {\n");
            sb.Append("  Terms: ").Append(Terms).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
