/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ManticoreSearch.Client.FileParameter;
using OpenAPIDateConverter = ManticoreSearch.Client.OpenAPIDateConverter;

namespace ManticoreSearch.Model
{
    /// <summary>
    /// Aggregation
    /// </summary>
    [DataContract(Name = "aggregation")]
    public partial class Aggregation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Aggregation" /> class.
        /// </summary>
        /// <param name="terms">terms.</param>
        /// <param name="sort">sort.</param>
        /// <param name="composite">composite.</param>
        /// <param name="histogram">histogram.</param>
        public Aggregation(AggTerms terms = default, List<Object> sort = default, AggComposite composite = default, AggHistogram histogram = default)
        {
            this.Terms = terms;
            this.Sort = sort;
            this.Composite = composite;
            this.Histogram = histogram;
        }

        /// <summary>
        /// Gets or Sets Terms
        /// </summary>
        [DataMember(Name = "terms", EmitDefaultValue = false)]
        public AggTerms Terms { get; set; }

        /// <summary>
        /// Gets or Sets Sort
        /// </summary>
        [DataMember(Name = "sort", EmitDefaultValue = false)]
        public List<Object> Sort { get; set; }

        /// <summary>
        /// Gets or Sets Composite
        /// </summary>
        [DataMember(Name = "composite", EmitDefaultValue = false)]
        public AggComposite Composite { get; set; }

        /// <summary>
        /// Gets or Sets Histogram
        /// </summary>
        [DataMember(Name = "histogram", EmitDefaultValue = false)]
        public AggHistogram Histogram { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Aggregation {\n");
            sb.Append("  Terms: ").Append(Terms).Append("\n");
            sb.Append("  Sort: ").Append(Sort).Append("\n");
            sb.Append("  Composite: ").Append(Composite).Append("\n");
            sb.Append("  Histogram: ").Append(Histogram).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
