/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ManticoreSearch.Client.FileParameter;
using OpenAPIDateConverter = ManticoreSearch.Client.OpenAPIDateConverter;

namespace ManticoreSearch.Model
{
    /// <summary>
    /// Specifies the location of the pin point used for search
    /// </summary>
    [DataContract(Name = "geoDistance_location_anchor")]
    public partial class GeoDistanceLocationAnchor : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoDistanceLocationAnchor" /> class.
        /// </summary>
        /// <param name="Lat">Latitude of the anchor point.</param>
        /// <param name="Lon">Longitude of the anchor point.</param>
        public GeoDistanceLocationAnchor(Object Lat = default(Object), Object Lon = default(Object))
        {
            this.Lat = Lat;
            this.Lon = Lon;
        }

        /// <summary>
        /// Latitude of the anchor point
        /// </summary>
        /// <value>Latitude of the anchor point</value>
        [DataMember(Name = "lat", EmitDefaultValue = true)]
        public Object Lat { get; set; }

        /// <summary>
        /// Longitude of the anchor point
        /// </summary>
        /// <value>Longitude of the anchor point</value>
        [DataMember(Name = "lon", EmitDefaultValue = true)]
        public Object Lon { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeoDistanceLocationAnchor {\n");
            sb.Append("  Lat: ").Append(Lat).Append("\n");
            sb.Append("  Lon: ").Append(Lon).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
