/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ManticoreSearch.Client.FileParameter;
using OpenAPIDateConverter = ManticoreSearch.Client.OpenAPIDateConverter;

namespace ManticoreSearch.Model
{
    /// <summary>
    /// Request object for knn search operation
    /// </summary>
    [DataContract(Name = "knnQueryByVector")]
    public partial class KnnQueryByVector : IEquatable<KnnQueryByVector>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KnnQueryByVector" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KnnQueryByVector() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KnnQueryByVector" /> class.
        /// </summary>
        /// <param name="field">field (required) (default to &quot;&quot;).</param>
        /// <param name="queryVector">queryVector (required).</param>
        /// <param name="k">k (required).</param>
        /// <param name="filter">filter.</param>
        public KnnQueryByVector(string field = "", List<decimal> queryVector = default(List<decimal>), int k = default(int), Dictionary<string, Object> filter = default(Dictionary<string, Object>))
        {
            // to ensure "field" is required (not null)
            if (field == null)
            {
                throw new ArgumentNullException("field is a required property for KnnQueryByVector and cannot be null");
            }
            this.Field = field;
            // to ensure "queryVector" is required (not null)
            if (queryVector == null)
            {
                throw new ArgumentNullException("queryVector is a required property for KnnQueryByVector and cannot be null");
            }
            this.QueryVector = queryVector;
            this.K = k;
            this.Filter = filter;
        }

        /// <summary>
        /// Gets or Sets Field
        /// </summary>
        [DataMember(Name = "field", IsRequired = true, EmitDefaultValue = false)]
        public string Field { get; set; }

        /// <summary>
        /// Gets or Sets QueryVector
        /// </summary>
        [DataMember(Name = "query_vector", IsRequired = true, EmitDefaultValue = false)]
        public List<decimal> QueryVector { get; set; }

        /// <summary>
        /// Gets or Sets K
        /// </summary>
        [DataMember(Name = "k", IsRequired = true, EmitDefaultValue = false)]
        public int K { get; set; }

        /// <summary>
        /// Gets or Sets Filter
        /// </summary>
        [DataMember(Name = "filter", EmitDefaultValue = false)]
        public Dictionary<string, Object> Filter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KnnQueryByVector {\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  QueryVector: ").Append(QueryVector).Append("\n");
            sb.Append("  K: ").Append(K).Append("\n");
            sb.Append("  Filter: ").Append(Filter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as KnnQueryByVector);
        }

        /// <summary>
        /// Returns true if KnnQueryByVector instances are equal
        /// </summary>
        /// <param name="input">Instance of KnnQueryByVector to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KnnQueryByVector input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Field == input.Field ||
                    (this.Field != null &&
                    this.Field.Equals(input.Field))
                ) && 
                (
                    this.QueryVector == input.QueryVector ||
                    this.QueryVector != null &&
                    input.QueryVector != null &&
                    this.QueryVector.SequenceEqual(input.QueryVector)
                ) && 
                (
                    this.K == input.K ||
                    this.K.Equals(input.K)
                ) && 
                (
                    this.Filter == input.Filter ||
                    this.Filter != null &&
                    input.Filter != null &&
                    this.Filter.SequenceEqual(input.Filter)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Field != null)
                {
                    hashCode = (hashCode * 59) + this.Field.GetHashCode();
                }
                if (this.QueryVector != null)
                {
                    hashCode = (hashCode * 59) + this.QueryVector.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.K.GetHashCode();
                if (this.Filter != null)
                {
                    hashCode = (hashCode * 59) + this.Filter.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
