/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ManticoreSearch.Client.FileParameter;
using OpenAPIDateConverter = ManticoreSearch.Client.OpenAPIDateConverter;

namespace ManticoreSearch.Model
{
    /// <summary>
    /// Filter helper object defining the &#39;match all&#39;&#39; condition
    /// </summary>
    [DataContract(Name = "match_all")]
    public partial class MatchAll : IValidatableObject
    {
        /// <summary>
        /// Defines All
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AllEnum
        {
            /// <summary>
            /// Enum  for value: {}
            /// </summary>
            [EnumMember(Value = "{}")]
            All = 1
        }

        /// <summary>
        /// Gets or Sets All
        /// </summary>
        [DataMember(Name = "_all", IsRequired = true, EmitDefaultValue = true)]
        public String All { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchAll" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MatchAll() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchAll" /> class.
        /// </summary>
        /// <param name="all">all (required).</param>
        public MatchAll(AllEnum all = default)
        {
            this.All = "{}";
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MatchAll {\n");
            sb.Append("  All: ").Append(All).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
