name: Publishing

on: [push]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    name: Publish the client to the public registry
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.APIKEY }}

    steps:
    - uses: actions/checkout@v4
    - run: |
       dotnet pack
       echo "Publish"
       ls


