name: Publishing

on: [push]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    name: Publish the client to the public registry
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.APIKEY }}

    steps:
    - uses: actions/checkout@v4
    - run: |
       NUPKG_FILEPATH=`dotnet pack | grep -o "/.*nupkg"``
       echo "Publish $NUPKG_FILEPATH"
       dotnet nuget push $NUPKG_FILEPATH --api-key $APIKEY --source https://api.nuget.org/v3/index.json

