name: tests

on: [workflow_call]

jobs:
  test:

    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    services:
      manticoresearch-manticore:
        image: manticoresearch/manticore:dev
        env:
          EXTRA: 1
        ports:
          - 9408:9308

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Test with dotnet
        run: dotnet test 
